services:
  metabase:
    image: metabase/metabase:v0.54.19.x
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3001:3000
    env_file: ".env"
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    env_file: ".env"
    networks:
      - metanet1
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  metanet1:
    driver: bridge

volumes:
  postgres_data: