services:
  devsql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: devsql
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    env_file: "default.env"
    ports:
      - "14333:1433"
    volumes:
      - mssqsl_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log
      - mssql_secrets:/var/opt/mssql/secrets

volumes:
  mssql_data:
  mssql_log:
  mssql_secrets:
