services:
  devsql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: devsql
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "sample@Strong23Password"
    ports:
      - "14333:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
